In [2]:
import numpy
n=numpy.arange(27)

In [6]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [1]:
import cv2

In [7]:
img_g=cv2.imread("smallgray.png", 0)
print(img_g)
# blue, green, red

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [6]:
cv2.imwrite("newsmallgray.png", img_g)

True

In [12]:
img_g[2, 4]

182

In [14]:
for i in img_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [15]:
for i in img_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [20]:
import numpy
ims=numpy.hstack((img_g, img_g, img_g))

In [22]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [23]:
ims = numpy.vstack((img_g, img_g, img_g))

In [24]:
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [29]:
lst = numpy.vsplit(ims, 3)
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)